export const siteConfig = {
  name: 'Sujith E',
  role: 'Aspiring AI Systems Engineer & Software Developer',
  headline: 'I build full-stack and AI-powered applications that actually ship.',
  tagline: 'CS undergraduate at PSG College of Technology — turning ideas into working software with JavaScript, Python, and the Gemini API.',
  email: 'sujith0718@gmail.com',
  location: 'Coimbatore, Tamil Nadu, India',
  github: 'https://github.com/sujith0718-coder',
  linkedin: 'https://www.linkedin.com/in/sujith-e-023362375/',
  resumeUrl: '/resume/Sujith_E_Resume.pdf',
  availableForWork: true,
};

export const stats = [
  { label: 'Projects Shipped', value: 9, suffix: '+' },
  { label: 'Technologies', value: 20, suffix: '+' },
  { label: 'Certifications', value: 6, suffix: '' },
  { label: 'Hackathons', value: 1, suffix: '' },
  { label: 'GitHub Repos', value: 9, suffix: '+' },
  { label: 'Cloud Deployments', value: 2, suffix: '' },
];

export const about = {
  story: `I'm a first-year Computer Science student at PSG College of Technology, Coimbatore — but I've been shipping real software since before university started.

I don't wait for coursework to validate my curiosity. I build things: REST APIs, AI productivity tools, full-stack web apps, Python visualizers. Each project is my way of stress-testing what I've learned and finding the edges of what I don't yet know.

My most honest summary: I'm comfortable being uncomfortable. Whether it's a 24-hour hackathon deadline or a new framework I've never touched, I lean into the constraint rather than away from it.`,

  philosophy: `I believe in building before theorizing. The fastest way to understand a concept is to break it in production.`,

  approach: `I start with the user problem, work backward to the architecture, and ship iteratively. I'd rather have a deployed MVP with rough edges than a perfect design document.`,

  mindset: [
    { title: 'Ownership', description: 'I treat every project like it\'s in production and users depend on it.' },
    { title: 'Curiosity-first', description: 'If I don\'t understand how something works under the hood, I dig until I do.' },
    { title: 'Bias to ship', description: 'Working software over comprehensive documentation. Always.' },
    { title: 'Continuous improvement', description: 'Every project makes the next one better. I track what broke and why.' },
  ],
};

export const skills = [
  {
    category: 'Languages',
    icon: 'Code2',
    color: 'blue',
    items: ['Python', 'JavaScript', 'TypeScript', 'C'],
  },
  {
    category: 'Frontend',
    icon: 'Layout',
    color: 'green',
    items: ['React', 'HTML5', 'CSS3', 'Responsive Design'],
  },
  {
    category: 'Backend',
    icon: 'Server',
    color: 'orange',
    items: ['Node.js', 'Flask', 'Express.js', 'REST API Design'],
  },
  {
    category: 'AI & Cloud',
    icon: 'Brain',
    color: 'purple',
    items: ['Google Gemini API', 'Prompt Engineering', 'Google AI Studio', 'Google Cloud Run'],
  },
  {
    category: 'Data & Formats',
    icon: 'Database',
    color: 'cyan',
    items: ['JSON', 'LocalStorage', 'REST APIs', 'HTTP'],
  },
  {
    category: 'Tools',
    icon: 'Wrench',
    color: 'yellow',
    items: ['Git', 'GitHub', 'Postman', 'VS Code'],
  },
  {
    category: 'Core CS',
    icon: 'BookOpen',
    color: 'red',
    items: ['Data Structures & Algorithms', 'Object-Oriented Programming', 'Full-Stack Development', 'AI Fundamentals'],
  },
  {
    category: 'Python Ecosystem',
    icon: 'Layers',
    color: 'teal',
    items: ['Streamlit', 'Flask', 'Python OOP', 'Modular Architecture'],
  },
];

export const projects = [
  {
    id: 'last-minute-ai',
    title: 'The Last-Minute Life Saver AI',
    subtitle: 'Hackathon Project',
    description: 'An AI-powered productivity assistant that helps overwhelmed users prioritize tasks and generate structured recovery plans under deadline pressure.',
    problem: 'People under deadline pressure lose clarity — they have too many tasks, too little time, and no structured system to think through what matters.',
    solution: 'Built a conversational AI interface using Google Gemini API that takes raw, chaotic task input and transforms it into structured, actionable priority plans with time estimates.',
    challenges: 'Designing prompts that consistently return structured, usable output across wildly different task descriptions. Also deploying a full Node.js + React app to Google Cloud Run under hackathon time pressure.',
    architecture: 'React + TypeScript frontend communicating with a Node.js backend that proxies requests to the Google Gemini API. Deployed containerized on Google Cloud Run for live demo access.',
    features: [
      'Real-time AI task prioritization via Gemini API',
      'Structured recovery plan generation from raw input',
      'Full-stack React + Node.js architecture',
      'Live deployment on Google Cloud Run',
      'Prompt-engineered for consistent, actionable output',
    ],
    stack: ['React', 'TypeScript', 'Node.js', 'Google Gemini API', 'Google Cloud Run'],
    github: 'https://github.com/sujith0718-coder/The-Last-Minute-Life-Saver',
    demo: 'https://last-minute-life-saver-ai-1096954303020.asia-southeast1.run.app/',
    featured: true,
    image: 'https://images.pexels.com/photos/5926389/pexels-photo-5926389.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: 'blue',
    badge: 'Hackathon',
  },
  {
    id: 'bookstore-api',
    title: 'Bookstore Management REST API',
    subtitle: 'Backend Engineering',
    description: 'A production-quality RESTful API with modular OOP architecture implementing complete HTTP method routing and JSON request/response handling for book inventory management.',
    problem: 'Needed to demonstrate clean backend architecture — not just "it works", but maintainable, testable, and correctly structured API design.',
    solution: 'Built with Flask using OOP principles, clean route separation, proper HTTP status codes, and comprehensive error handling. All endpoints validated through Postman.',
    challenges: 'Designing a modular architecture in Flask that would hold up at scale — separating concerns between routes, business logic, and data models without over-engineering.',
    architecture: 'Python + Flask with OOP-based modular design. RESTful routing with proper HTTP semantics. JSON request/response with validated error states.',
    features: [
      'Full CRUD operations with correct HTTP semantics',
      'OOP-based modular architecture',
      'JSON request/response with error handling',
      'Postman-validated endpoint coverage',
      'Custom status codes and error messages',
    ],
    stack: ['Python', 'Flask', 'REST API', 'JSON', 'Postman'],
    github: 'https://github.com/sujith0718-coder/bookstore-rest-api',
    demo: null,
    featured: true,
    image: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: 'green',
    badge: 'Backend',
  },
  {
    id: 'nodejs-server',
    title: 'Node.js Web Server',
    subtitle: 'Systems Programming',
    description: 'A custom HTTP server built entirely from Node.js core modules — no frameworks — capable of serving HTML, CSS, JS, images, and JSON with routing, redirects, and error handling.',
    problem: 'Frameworks abstract away HTTP fundamentals. Built this to prove I understand what\'s happening underneath Express — routing, MIME types, status codes, and the event loop.',
    solution: 'Custom HTTP server using only Node.js built-ins. Implements full routing, redirects, custom 404 pages, request logging via EventEmitter, and multi-format file serving.',
    challenges: 'Correctly handling MIME types for different file formats, implementing redirect chains, and building a proper EventEmitter-based request logger without leaking listeners.',
    architecture: 'Pure Node.js core modules. No npm dependencies. EventEmitter for logging, fs module for file serving, manual MIME type mapping for all content types.',
    features: [
      'Zero-framework HTTP server',
      'Multi-format file serving (HTML, CSS, JS, images, JSON)',
      'Custom routing and redirect handling',
      '404 and error page handling',
      'Request logging via EventEmitter',
    ],
    stack: ['Node.js', 'JavaScript', 'HTTP', 'EventEmitter'],
    github: 'https://github.com/sujith0718-coder/nodejs-web-server',
    demo: null,
    featured: true,
    image: 'https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: 'orange',
    badge: 'Systems',
  },
  {
    id: 'student-compass',
    title: 'Student Compass',
    subtitle: 'Full-Stack Web App',
    description: 'A student guidance platform delivering semester roadmaps and progress tracking for first-year engineering students, with data persisted via LocalStorage.',
    problem: 'First-year engineering students have no structured visibility into what they should be learning each semester and how they\'re progressing.',
    solution: 'Built a guidance platform with curated semester roadmaps, interactive progress tracking, and persistent data — so students always resume where they left off.',
    challenges: 'Designing a data model for progress tracking that is flexible enough for different learning paths but simple enough to persist cleanly in LocalStorage.',
    architecture: 'Vanilla JavaScript SPA with structured LocalStorage data model. Modular component-style JS without a framework.',
    features: [
      'Semester-by-semester learning roadmaps',
      'Interactive progress tracking',
      'Persistent data via LocalStorage',
      'First-year engineering curriculum focus',
      'Responsive, accessible design',
    ],
    stack: ['HTML', 'CSS', 'JavaScript', 'LocalStorage'],
    github: 'https://github.com/sujith0718-coder/Student-Compass',
    demo: 'https://sujith0718-coder.github.io/Student-Compass/',
    featured: false,
    image: 'https://images.pexels.com/photos/5212329/pexels-photo-5212329.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: 'purple',
    badge: 'Education',
  },
  {
    id: 'class-info-system',
    title: 'Class Information System',
    subtitle: 'Full-Stack Web App',
    description: 'A classroom management dashboard with full CRUD operations, search and filtering, exam countdowns, and persistent LocalStorage-backed data.',
    problem: 'Class data management is fragmented — student records, exam dates, and schedules live in different places with no unified view.',
    solution: 'Built a unified dashboard with searchable student records, real-time exam countdowns, and full CRUD functionality with persistent data.',
    challenges: 'Building a real-time countdown system that stays accurate across page reloads, and designing a search/filter system that handles multiple simultaneous filter criteria.',
    architecture: 'Vanilla JS with structured data model in LocalStorage. Real-time countdown engine with setInterval. Dynamic DOM manipulation for search/filter.',
    features: [
      'Full CRUD for student and class records',
      'Real-time exam countdown timers',
      'Search and multi-criteria filtering',
      'LocalStorage data persistence',
      'Clean, functional dashboard UI',
    ],
    stack: ['HTML', 'CSS', 'JavaScript', 'LocalStorage'],
    github: 'https://github.com/sujith0718-coder/Class-Information-System',
    demo: 'https://sujith0718-coder.github.io/Class-Information-System/',
    featured: false,
    image: 'https://images.pexels.com/photos/5212330/pexels-photo-5212330.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: 'cyan',
    badge: 'Dashboard',
  },
  {
    id: 'fourier-visualizer',
    title: 'Fourier Series Visualizer',
    subtitle: 'Python & Data Visualization',
    description: 'An interactive Fourier series visualizer built with Python and Streamlit, making abstract mathematics tangible through real-time visual feedback.',
    problem: 'Fourier series are notoriously abstract — textbook explanations rarely convey the intuition. Needed a tool that shows, not tells.',
    solution: 'Built an interactive Streamlit app where users control wave parameters and instantly see how harmonics combine to approximate waveforms.',
    challenges: 'Balancing mathematical accuracy with visual clarity, and building a Streamlit interface that stays performant with real-time parameter updates.',
    architecture: 'Python + Streamlit with NumPy for signal computation and Matplotlib for rendering. Reactive parameter controls via Streamlit widgets.',
    features: [
      'Interactive wave parameter controls',
      'Real-time Fourier series visualization',
      'Multiple harmonic component display',
      'Mathematical accuracy with visual clarity',
      'Streamlit-powered reactive UI',
    ],
    stack: ['Python', 'Streamlit', 'NumPy', 'Matplotlib'],
    github: 'https://github.com/sujith0718-coder/fourier-series-app',
    demo: 'https://fourier-series-app-itiug7fkhjkhwnzeabl9le.streamlit.app/',
    featured: false,
    image: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: 'teal',
    badge: 'Math & Viz',
  },
];

export const timeline = [
  {
    year: '2026',
    month: 'Jun',
    title: 'Hackathon: Built AI Productivity Tool',
    description: 'Shipped "The Last-Minute Life Saver AI" — a full-stack AI application using React, Node.js, Google Gemini API, and deployed live on Google Cloud Run.',
    type: 'hackathon',
    highlight: true,
  },
  {
    year: '2026',
    month: 'Jun',
    title: 'Google Cloud Run Deployment',
    description: 'First live cloud deployment — containerized a Node.js + React application and deployed to Google Cloud Run for production-level public access.',
    type: 'achievement',
    highlight: true,
  },
  {
    year: '2025',
    month: 'Dec',
    title: 'Completed Infosys Springboard: Python',
    description: 'Completed structured Python fundamentals course through Infosys Springboard, reinforcing OOP, data structures, and Pythonic code patterns.',
    type: 'certification',
    highlight: false,
  },
  {
    year: '2026',
    month: 'Jul',
    title: 'Built Bookstore REST API',
    description: 'Designed and built a production-quality RESTful API in Flask with OOP architecture. Validated all endpoints with Postman.',
    type: 'project',
    highlight: false,
  },
  {
    year: '2026',
    month: 'Jul',
    title: 'GitHub Skills Certifications',
    description: 'Completed GitHub\'s official Introduction to Git and Introduction to GitHub courses. Established consistent version control practice across all projects.',
    type: 'certification',
    highlight: false,
  },
  {
    year: '2026',
    month: 'Jul',
    title: 'AI Tools & ChatGPT Workshop',
    description: 'Attended AI Tools & ChatGPT workshop — first structured exposure to prompt engineering principles that later informed Gemini API work.',
    type: 'learning',
    highlight: false,
  },
  {
    year: '2024',
    month: 'Jun',
    title: 'Higher Secondary Education Completed',
    description: 'Completed Higher Secondary at Bethel Matriculation Higher Secondary School, Ambur. Began building personal projects in preparation for CSE undergraduate program.',
    type: 'education',
    highlight: false,
  },
  {
    year: '2025',
    month: 'Jan',
    title: 'Started B.E. CSE at PSG College of Technology',
    description: 'Began Computer Science and Engineering degree at PSG College of Technology, Coimbatore — one of India\'s top engineering institutions.',
    type: 'education',
    highlight: true,
  },
];

export const differentiators = [
  {
    icon: 'Zap',
    title: 'Ships Under Pressure',
    description: 'Completed a full-stack AI application — including prompt engineering, backend, and cloud deployment — under hackathon deadline conditions. Not a prototype. A working product.',
  },
  {
    icon: 'Brain',
    title: 'AI-Native Builder',
    description: 'Integrating LLMs into real products before it was a university requirement. Understands the difference between using AI and building with AI.',
  },
  {
    icon: 'Layers',
    title: 'Full-Stack Breadth',
    description: 'Comfortable from HTTP-level Node.js server code to React frontends to Python Flask APIs. No layer is a black box.',
  },
  {
    icon: 'BookOpen',
    title: 'Learns by Building',
    description: 'Every new concept becomes a project. Fourier series become a Streamlit visualizer. HTTP fundamentals become a from-scratch Node.js server.',
  },
  {
    icon: 'Target',
    title: 'Problem-First Thinker',
    description: 'Projects start with a real problem to solve, not a technology to demonstrate. The tech stack follows the problem — not the other way around.',
  },
  {
    icon: 'TrendingUp',
    title: 'Evidence Over Claims',
    description: '9+ deployed or submitted projects in less than a year, built entirely outside of coursework. The GitHub history speaks louder than a resume line.',
  },
];

export const certifications = [
  { title: 'AI Tools & ChatGPT Workshop', issuer: 'Workshop', year: '2026' },
  { title: 'Basics of Python', issuer: 'Infosys Springboard', year: '2025' },
  { title: 'Introduction to C Programming', issuer: 'SoloLearn', year: '2026' },
  { title: 'Introduction to Git', issuer: 'GitHub Skills', year: '2026' },
  { title: 'Introduction to GitHub', issuer: 'GitHub Skills', year: '2026' },
  { title: 'Skill Development Awareness Program', issuer: 'Program', year: '2026' },
];

export const additionalProjects = [
  { title: 'Fourier Series Visualizer', stack: 'Python, Streamlit', github: 'https://github.com/sujith0718-coder/fourier-series-app' },
  { title: 'Booksky', stack: 'HTML, CSS, JavaScript', github: 'https://github.com/sujith0718-coder/Booksky' },
  { title: 'Student Form Management System', stack: 'HTML, CSS, JavaScript, LocalStorage', github: 'https://github.com/sujith0718-coder/STUDENT-FORM' },
  { title: 'Perfumy Website', stack: 'HTML, CSS', github: 'https://github.com/sujith0718-coder/perfumy' },
];
